### ISSUE TITLE
Mapping between string in image_name and number in labels

### ISSUE THREAD

**Issue by irvingwu5** [RomGai/BrainVis#12]
![微信图片_20240811220040](https://github.com/user-attachments/assets/403f1bb9-d5d7-4173-9391-8ab5e348cdc8)
Hi, I want to ask you a question please, what is the mapping between strings in image_names and numbers in labels? Thank you very much for taking the time to answer my questions

**Comment by RomGai** [comment]
This is determined by the dataset we used. In fact, it seems that the dataset's official source does not provide the corresponding mapping relationships. 

However, since the prefix 'n03452741' of the image represents the class name, I manually mapped it based on the labels and the actual corresponding images. You can find the corresponding mapping in the 'lable_number_dict' variable in 'cascade_diffusion.py'.

**Comment by irvingwu5** [comment]
> This is determined by the dataset we used. In fact, it seems that the dataset's official source does not provide the corresponding mapping relationships.
> 
> However, since the prefix 'n03452741' of the image represents the class name, I manually mapped it based on the labels and the actual corresponding images. You can find the corresponding mapping in the 'lable_number_dict' variable in 'cascade_diffusion.py'.

Thank you very much for your answer! Have a good day!
