### ISSUE TITLE
May I ask which of your papers has been accepted at ACM Multimedia

### ISSUE THREAD

**Issue by xiangxinhello** [RomGai/BrainVis#13]
May I ask which of your papers has been accepted at ACM Multimedia

**Comment by RomGai** [comment]
Only this paper was submitted to MM, and unfortunately it was not accepted.

**Comment by xiangxinhello** [comment]
> Only this paper was submitted to MM, and unfortunately it was not accepted.

What is the reason for being rejected?

**Comment by RomGai** [comment]
Perhaps the reason is misfortune. Here is one of the reviewers' comments:

1. Although the authors claim that BrainVis exceeds previous methods in low-level metrics such as SSIM, the model design does not have the pixel-level design of EEG decoding and therefore lacks a reasonable explanation. 
**(However, we have never claimed that our method is better than other methods in low-level metrics.)**

2. In the design of the cascade diffusion model, the second generation is considered coarse-grained control due to the control condition being simple category text. However, the authors claim that Sample2 of BrainVis in Figure 6 has more accurate fine-grained information, which is inconsistent. A more plausible explanation is the pixel-level uncontrollability caused by the text-to-image diffusion model when generating the image.
**(This reviewer confused high-level fine-grained semantics with low-level pixels. Moreover, both Sample 1 and Sample 2 are final results; we never claimed that Sample 2 of BrainVis in Figure 6 has more accurate fine-grained information. I think he/she haven't done a basic reading of our paper.)**

3. Carrying on from the above, it is worrying that BrainVis generates images that rely exclusively on higher classification accuracy, with more accurate category text leading to better results. However, the introduction of the frequency domain in EEG classification tasks is not novel, which has been used in a large body of literature [1, 2]. The authors need to measure the usefulness of frequency domain features for the first stage of BrainVis to reconstruct images, not just classification.
**(Completely overlooked our objective of reconstructing fine-grained semantics. This stems from the misunderstanding of "fine-grained" and "pixel-level.")**

I think these negative comments are unfair. 

Btw, it is also related to our lack of clarity in writing, so the entire paper has recently been reorganized.

**Comment by RomGai** [comment]
There are some unfair negative comments. It might be related to our lack of clarity in writing, so the entire paper has recently been reorganized.
