### ISSUE TITLE
Test dataset questions

### ISSUE THREAD

**Issue by Levi-arch1** [RomGai/BrainVis#15]
Dear author, hello. I have gained a lot from your work. With your help and guidance, the model training was successfully completed. But there is still a question during the testing phase. If I want to use my own collected EEG data for testing, how should I organize my testing dataset? What format should the dataset be processed into? I don't think the input data is directly collected as .bdf or .edf. Looking forward to your answer, thank you very much.

**Comment by RomGai** [comment]
Hello, very pleased to hear that you have successfully trained the model. 

Since the data we used comes from a pre-processed dataset, our work did not involve much data preprocessing. The dataset should consist of EEG signals and their corresponding images. During classification training, EEG signals and their corresponding image labels (in one-hot format) were used. You can refer to the dataset we used in the paper.

However, for customized data, you may need to train and test on your own data, as the data distribution of different datasets can vary significantly.

**Comment by RomGai** [comment]
You can try extracting the time series data from .bdf or .edf files and save it as a .pth file. I believe the MNE library might be helpful for you.
