### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by elelo22** [RomGai/BrainVis#5]
Hi, nice work! Is it possible to have checkpoints of your models?

Thank you!

**Comment by RomGai** [comment]
No problem, can you tell me your email and I will send you a download link.

**Comment by elelo22** [comment]
My email is eleonora.lopez@uniroma1.it, thank you so much!

**Comment by RomGai** [comment]
Done~

I do not wish for the checkpoint to be publicly available for download because we have discovered that models based on Stable Diffusion can generate some NSFW images, which pose legal risks in my region. However, we have implemented restrictions on this in the code we published on GitHub. Thanks for your understanding!
